### ISSUE TITLE
Create Roadmap for Connectors Workgroup

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/Connectors#7]
The following bullet point represent initial ideas on how the connectors workgroup can contribute to the ms 2 and the implementation of the different POCs:

### Prototype 0.5
- [x] Apply adapter quality guidelines (snazzy + silverERP + 2 further applications)
  - [x] Check Documentation
  - [x] Check object coverage
  - [x] Check functionality 
- [x] Apply transformer quality guidelines (snazzy + silverERP + 2 further applications)

### Procedure model for integration of cloud provider
-  Incorporate lessons learned from the integration of the two further domains
   - [ ] Adjust existing adapter guidelines
   - [ ] Create transformer guidelines (including a checklist) in collaboration with the data & domain model workgroup

### POC 2
- Decoupling of ISV applications using Connectors
   - [ ] Apply adapter quality guidelines on Snazzy and SilverERP adapter
### POC 3
- ISV specific connector component includes adapter and transformer modules to interact with the OIH Smart Data Framework
   - [ ] Creation of guidelines for building a transformer in collaboration with data & domain model workgroup (See contribution to MS 2)
   - [ ] Requirements to test a transformer

**Comment by philecs** [comment]
- Versioning of the `quality guidelines`

**Comment by philecs** [comment]
Prepare guidelines for external presentation
- [ ] Create quality checklists from the transformer guidelines
- [ ] Communicate the guidelines to the `community & marketing` workgroup

**Comment by RobinBrinkmann** [comment]
The process for versioning (guideline and connectors) will be designed in a scalable and resuable way so it can function as part of quality assurance once OIH is public.

In order to make it easy for developers to engage with OIH, we will present the guidelines not only in writing on GitHub. Other forms can be live workshops, recorded sessions or reference cases. These efforts and communication of the outcome will be supported by `community & marketing` workgroup. 

In order to record such a session, we need a relatively stable version of guidelines. The goal is to have a first outcome in May 2018.

**Comment by philecs** [comment]
As we work closely with the data & domain model on the transformation guidelines, it is necessary to understand of which parts the transformer guidelines consist and who is responsible for the distinct parts.

Currently we consider the guidelines to consist of the following parts:

- Mapping
- Quality Checks (analogous to the adapter completeness checklists)

From previous discussions the the following questions came up:

- [ ] What should be part of the transformer guidelines?
- [ ] What further parts could be part of the guidelines?
- [ ] What should be part of the "mapping" part?

In order to write complete guidelines and contribute to the MS 2 / POCs, we need to find answers for these questions.
