### ISSUE TITLE
Open Questions Transformer

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/Connectors#8]
As we work closely with the data & domain model on the transformation guidelines, it is necessary to understand of which parts the transformer guidelines consist and who is responsible for the distinct parts.

Currently we consider the guidelines to consist of the following parts:
- Mapping
- Quality Checks (analogous to the adapter completeness checklists)

From previous discussions the the following questions came up:

- [ ] What exactly is the transformer?
- [ ] What should be part of the transformer guidelines?
  - [ ] What further parts could be part of the guidelines?
  - [ ] What should be part of the "mapping" part?

In order to write complete guidelines and contribute to the MS 2 / POCs, we need to find answers for these questions.
